### ISSUE TITLE
Reply doesn't disappear after api key is sent

### ISSUE THREAD

**Issue by Martinligabue** [KnorpelSenf/cloudconvert-bot#2]
when the message
Perfect! Now send me the API key in reply to this message!
appears, I reply with api key, after that the bot make me autoreply again to that message.
Could it be something not closed?

**Comment by KnorpelSenf** [comment]
Are you on TDesktop? This is a problem I know from there, but it has nothing to do with the bot. It can only force clients to show a reply when a message is sent (via message extra options).

**Comment by Martinligabue** [comment]
f
